<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251123004720 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE discussion_ia (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, prompt TEXT NOT NULL, reponse_ia TEXT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, projet_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6AB4279EC18272 ON discussion_ia (projet_id)');
        $this->addSql('CREATE TABLE projet (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(255) NOT NULL, description TEXT NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, utilisateur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_50159CA9FB88E14F ON projet (utilisateur_id)');
        $this->addSql('CREATE TABLE utilisateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, nom VARCHAR(255) NOT NULL, date_inscription TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1D1C63B3E7927C74 ON utilisateur (email)');
        $this->addSql('ALTER TABLE discussion_ia ADD CONSTRAINT FK_6AB4279EC18272 FOREIGN KEY (projet_id) REFERENCES projet (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE projet ADD CONSTRAINT FK_50159CA9FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE discussion_ia DROP CONSTRAINT FK_6AB4279EC18272');
        $this->addSql('ALTER TABLE projet DROP CONSTRAINT FK_50159CA9FB88E14F');
        $this->addSql('DROP TABLE discussion_ia');
        $this->addSql('DROP TABLE projet');
        $this->addSql('DROP TABLE utilisateur');
    }
}
